FROM tensorflow/tensorflow:1.15.0-gpu-py3

RUN pip install torch torchvision
RUN pip install tensorboardX
RUN pip install scipy==1.3.3
RUN pip install requests==2.22.0
RUN pip install Pillow==6.2.1
RUN pip install opencv-python
RUN pip install opencv-contrib-python
RUN pip install scikit-learn
RUN pip install scikit-image
RUN pip install matplotlib
RUN pip install numpy
RUN pip install numba
RUN pip install pandas
RUN pip install tqdm
RUN pip install progressbar
RUN pip install mtcnn
RUN pip install facenet-pytorch
RUN pip install nltk
RUN pip install pickle-mixin
RUN pip install regex
RUN pip install pyparsing
RUN pip install boto3==1.9.227
RUN pip install botocore==1.12.227
RUN pip install certifi==2019.9.11
RUN pip install chardet==3.0.4
RUN pip install Click==7.0
RUN pip install cycler==0.10.0
RUN pip install docutils==0.15.2
RUN pip install idna==2.8
RUN pip install jmespath==0.9.4
RUN pip install joblib==0.13.2
RUN pip install kiwisolver==1.1.0
RUN pip install python-dateutil==2.8.0
RUN pip install transformers==2.5.1
RUN pip install pytz==2019.2
RUN pip install s3transfer==0.2.1
RUN pip install sacremoses==0.0.33
RUN pip install sentencepiece==0.1.83
RUN pip install six==1.12.0
RUN pip install urllib3==1.25.3
